seed: 42

model: !!python/object/apply:tensorflow.keras.models.Sequential
  args:
    - !!python/list
      - !!python/object/apply:tensorflow.keras.layers.Flatten
        kwds: {input_shape: !!python/tuple [28, 28]}
      - !!python/object/apply:tensorflow.keras.layers.Dense
        args: [128]
        kwds: {activation: relu}
      - !!python/object/apply:tensorflow.keras.layers.Dropout
        args: [0.2]
      - !!python/object/apply:tensorflow.keras.layers.Dense
        args: [10]

data_loader: !!python/name:tensorflow.python.keras.datasets.mnist.load_data

compile_kwds:
  loss: !!python/object/apply:tensorflow.python.keras.losses.SparseCategoricalCrossentropy
    kwds: {from_logits: true}
  metrics: [accuracy]
  optimizer: adam

fit_kwds:
  epochs: 5
  batch_size: 32
  shuffle: True
  validation_split: 0.1
