seed: 42
name: &name mnist_callbacks

mlflow:
  experiment_name: *name
  log_artifacts: $base_path
  log_params:
    hidden_units: &units 128
  set_tags:
    name: *name

model: !!python/object/apply:tensorflow.keras.models.Sequential
  args:
    - !!python/list
      - !!python/object/apply:tensorflow.keras.layers.Flatten
        kwds: {input_shape: !!python/tuple [28, 28]}
      - !!python/object/apply:tensorflow.keras.layers.Dense
        args: [*units]
        kwds: {activation: relu}
      - !!python/object/apply:tensorflow.keras.layers.Dropout
        args: [0.2]
      - !!python/object/apply:tensorflow.keras.layers.Dense
        args: [10]

data_loader: !!python/name:tensorflow.python.keras.datasets.mnist.load_data

model_checkpoints: !join 
  - !store 
    - base_path
    - !abspathjoin
      - logs
      - *name
  - '/mcp'

compile_kwds:
  loss: !!python/object/apply:tensorflow.python.keras.losses.SparseCategoricalCrossentropy
    kwds: {from_logits: true}
  metrics: [accuracy]
  optimizer: adam

fit_kwds:
  epochs: 5
  batch_size: 32
  shuffle: True
  validation_split: 0.1
  callbacks:
    !include inc/callbacks.yaml

